set(MY_TARGET_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/ecstrings")

set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${MY_TARGET_OUTPUT_DIRECTORY}")
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY "${MY_TARGET_OUTPUT_DIRECTORY}")
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${MY_TARGET_OUTPUT_DIRECTORY}")
